spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:nacos:8848}
      config:
        server-addr: ${NACOS_ADDR:nacos:8848}
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:sentinel-dashboard:8858}

aetherflow:
  gateway:
    security:
      auth-enabled: true
